In [ ]:
print('Welcome to Shiash...')

Welcome to Shiash...


In [ ]:
print(10 + 5)

15


In [ ]:
num1 = 5000
print(num1, id(num1))
num = 5000
print(num, id(num))

5000 133198502857872
5000 133198502857648


In [ ]:
a=10
a

10

In [ ]:
a=10
b=20
a+b

30

In [ ]:
# dynamically typed

num = 10 # integers -> 4 byte
print(num, type(num))

num = 10.5 # float -> 8 bytes
print(num, type(num))

num = 'vasanth' # char -> each character takes 1 byte -> 7 bytes
print(num, type(num))

num = 'a' # 1 byte
print(num, type(num))

num = False # True -> 1 byte
print(num, type(num))

10 <class 'int'>
10.5 <class 'float'>
vasanth <class 'str'>
a <class 'str'>
False <class 'bool'>


In [ ]:
a = '10'
b = 5
#print(a + b) # typeerror -> str cant concat with int


a = '10'
b = '5'
print(a + b)

a = False
b = 5
print(a + b)

a = True
b = False
print(a + b)


# pascal case -> FirstName, LastName -> class
# camel case -> firstOfName, lastOfName -> not used
# snake case -> first_name, last_name, age_of_person -> variables(nouns), functions(action   verbs)

105
5
1


In [ ]:
name,age = "Suresh",29
print(name,age,"is a \"natural\" swimmer")


Suresh 29 is a "natural" swimmer


In [ ]:
 # strings
first_name = 'sachin'
last_name = 'tendulkar'

# sachin tendulkar is a good cricketer
print(first_name, last_name, 'is a good cricketer')

# 'sachin tendulkar' is a good cricketer
# print("'" + first_name + " "  + last_name + "'" + "is a good cricketer")

# formatted strings
 print(f" '{first_name} {last_name}' is a good cricketer")

# "sachin tendulkar" is a good cricketer
# print(f' "{first_name} {last_name}" is a good cricketer')

# "sachin tendulkar" is a 'good' cricketer
# ''' ''' or """ """
print(f""" "{first_name} {last_name}" is a 'good' cricketer""")
print(f''' "{first_name} {last_name}" is a 'good' cricketer ''')

# triple quotes is primarily used for multiline strings
poem = """Johnny johhny yes papa
eat sugar no papa
telling lies no papa
open your mouth hahaha"""

print(poem)

sachin tendulkar is a good cricketer
 'sachin tendulkar' is a good cricketer
 "sachin tendulkar" is a 'good' cricketer
 "sachin tendulkar" is a 'good' cricketer 
Johnny johhny yes papa
eat sugar no papa
telling lies no papa
open your mouth hahaha


In [ ]:
num1 = input('Enter the num1: ')
num2 = input('Enter the num2: ')
print(type(num1), type(num2), num1, num2)

# process of converting one data type to another data type is called typecasting
num1 = int(num1)
num2 = int(num2)
print(type(num1), type(num2), num1 + num2)

# num1 = float(num1)
# num2 = float(num2)
# print(type(num1), type(num2), num1 + num2)

# print(int(10.5), int('10.5'))

# any number -> bool -> True
# 0 -> bool -> False
num1 = bool(int(num1))
num2 = bool(int(num2))
print(num1, num2, type(num2))

Enter the num1: 12
Enter the num2: 23
<class 'str'> <class 'str'> 12 23
True True <class 'bool'>


In [ ]:
# strings
name = 'poonam'
# P O O N A M
# 0 1 2 3 4 5
print(name)
print(name[0], name[1], name[2], name[3], name[4], name[5], name[6]) # index error

poonam


In [ ]:
# strings are immutable ->
country = 'INDIA'
# print(country[0])
# country[0] = 'J' # type error
# JNDIA
country = 'australia'
print(country)

australia


In [ ]:
name = 'sHiPra sIngla is a good singer'
print(name.upper())
print(name.lower())
print(name.capitalize())
print(name.title())

SHIPRA SINGLA IS A GOOD SINGER
shipra singla is a good singer
Shipra singla is a good singer
Shipra Singla Is A Good Singer


In [ ]:
# strip
game = '             god of war        '
print("Length         :",game, len(game))
print(game.strip(), len(game.strip())) # default it'll take space
game = 'racecar'
print("Strip          :",game.strip('r')) # both beginning and ending chars of the string
print("Left Strip     :",game.lstrip('r'))
print("Right Strip    :",game.rstrip('r'))
print("Lower Case     :",game.islower())
print("Upper Case     :",game.isupper())
print("is digits      :",game.isdigit())
print("is alphabetic  :",game.isalpha())
print("is alphanumeric:",game.isalnum())
print("Starts with  r :",game.startswith('r'))
print("ends with r    :",game.endswith('r'))
print("Replace with   :",game.replace('race', 'run'))
print("count of r     :",game.count('r'))
print("find           :",game.find('car'))
print("index of       :",game.index('car'))
print("index of       :",game.split(' '))
print("swap case      :",game.swapcase())
print("title          :",game.title())
print("center         :",game.center(20, '#'))
print("zfill          :",game.zfill(20))

Length         :              god of war         31
god of war 10
Strip          : aceca
Left Strip     : acecar
Right Strip    : raceca
Lower Case     : True
Upper Case     : False
is digits      : False
is alphabetic  : True
is alphanumeric: True
Starts with  r : True
ends with r    : True
Replace with   : runcar
count of r     : 2
find           : 4
index of       : 4
index of       : ['racecar']
swap case      : RACECAR
title          : Racecar
center         : ######racecar#######
zfill          : 0000000000000racecar


In [ ]:
game = 'racecar'
print("find           :",game.find('car'))

find           : 4


In [ ]:
systolic=int(input("Enter sys").strip())
diastolic=int(input("Enter dias").strip())
if ((systolic>120 & systolic<129) & (diastolic <80)):
  print("Elevated BP")
elif ((systolic>180) & (diastolic >120)):
  print("Hypertension")
else:
  print("not")

Enter sys345
Enter dias300
Hypertension


In [ ]:
#program to generate image file names randomly
image_numbers = [1, 12, 5, 123]
for num in image_numbers:
    filename = f"image_{str(num).zfill(4)}.png"
    print(filename)

image_0001.png
image_0012.png
image_0005.png
image_0123.png


In [ ]:
name=['d','e','e','p','i','k','a']
print(name[0::2])

['d', 'e', 'i', 'a']


In [ ]:
language = 'Python  is a PPP good language'
# print(language.replace('  ', ' '))
print(language.replace('P', 'C')) # all the P will be replaced by C
print(language.replace('P', 'C', 2)) # count
print(language)
print(language[::-1])
language.split(' ')
language.find('good')


Cython  is a CCC good language
Cython  is a CPP good language
Python  is a PPP good language
egaugnal doog PPP a si  nohtyP


17

In [ ]:
#Write a program to check Palindrome or not

In [ ]:
a=input("Enter a string: ")
s=a[::-1]
if s==a:
    print("Yes, it's a palindrome!")
else:
    print("No, it's not a palindrome.")

Enter a string: fghdf
No, it's not a palindrome.


In [ ]:
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

text = "Hello, World!"
print(f"Number of vowels in '{text}': {count_vowels(text)}")
# Output: Number of vowels in 'Hello, World!': 3

In [ ]:
def is_palindrome(s):
    s = s.lower().replace(" ", "")  # Normalize the string
    return s == s[::-1]

text1 = "A man a plan a canal Panama"
text2 = "Hello, World!"
print(f"'{text1}' is a palindrome: {is_palindrome(text1)}")
# Output: 'A man a plan a canal Panama' is a palindrome: True
print(f"'{text2}' is a palindrome: {is_palindrome(text2)}")
# Output: 'Hello, World!' is a palindrome: False

In [ ]:
def check(string):
    if len(set(string.lower()).intersection("aeiou")) >= 5:
        return ('accepted')
    else:
        return ("not accepted")


string = "aeiou"
print(check(string))

accepted


The original string is : zero four zero one
The string after performing replace : 0401


In [ ]:
original_string = 'zero four zero one'

result = ''.join(['0' if word == 'zero' else '1' if word == 'one' else '2' if word == 'two' else '3' if word == 'three' else '4' if word == 'four' else '5' if word == 'five' else '6' if word == 'six' else '7' if word == 'seven' else '8' if word == 'eight' else '9' for word in original_string.split()])

print(result)

In [ ]:
# Defining the Function
def EvenOdd(n):
  print("Even Number") if(n%2 == 0) else print("Odd Number")

# Calling the Function:
EvenOdd(21) # Output: Odd Number
EvenOdd(12) # Output: Even Number

Odd Number
Even Number


In [ ]:
s=input( )
print(sorted(s))

gfdfgsertergdf
['d', 'd', 'e', 'e', 'f', 'f', 'f', 'g', 'g', 'g', 'r', 'r', 's', 't']


In [ ]:
a=input("enter the name ")
b=input("enter the name ")
c = a + b
sorted_c = sorted(c)
result = ''.join(sorted_c)
print("Sorted c of the names:", result)


enter the name rfghghj
enter the name ghjghjg
Sorted c of the names: fggggghhhhjjjr


In [ ]:
a = 10
b = 20
print(a>b)

False


In [ ]:
a = 10
b = 10.0
print(a is not b)

True


In [ ]:
a = [10]
b = {10,20}
print(a[0] in b)

True


In [ ]:
a = 10
b = 20
print(a > 5 & b > 15)

False


In [ ]:
a = 10
b = 20
print(a > 5 or b > 15)

True


In [ ]:
# Create a list
my_list = [3, 1, 4, 1, 5, 9, 2, 6]

# Append an element
my_list.append(5)
print(my_list)  # Output: [3, 1, 4, 1, 5, 9, 2, 6, 5]

# Extend the list
my_list.extend([3, 5])
print(my_list)  # Output: [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]

# Insert an element at a specific position
my_list.insert(2, 7)
print(my_list)  # Output: [3, 1, 7, 4, 1, 5, 9, 2, 6, 5, 3, 5]

# Remove an element
my_list.remove(1)
print(my_list)  # Output: [3, 7, 4, 1, 5, 9, 2, 6, 5, 3, 5]

# Pop an element
popped_element = my_list.pop(3)
print(popped_element)  # Output: 1
print(my_list)         # Output: [3, 7, 4, 5, 9, 2, 6, 5, 3, 5]

# Clear the list
my_list.clear()
print(my_list)  # Output: []

# Recreate a list for further methods
my_list = [3, 1, 4, 1, 5, 9, 2, 6]

# Find the index of an element
index_of_4 = my_list.index(4)
print(index_of_4)  # Output: 2

# Count occurrences of an element
count_of_1 = my_list.count(1)
print(count_of_1)  # Output: 2

# Sort the list
my_list.sort()
print(my_list)  # Output: [1, 1, 2, 3, 4, 5, 6, 9]

# Reverse the list
my_list.reverse()
print(my_list)  # Output: [9, 6, 5, 4, 3, 2, 1, 1]

# Copy the list
my_list_copy = my_list.copy()
print(my_list_copy)  # Output: [9, 6, 5, 4, 3, 2, 1, 1]

In [ ]:
a = [1,2,3,4,5]

b = [2,3,4,5,6]

print(a[-1],"and",b[len(b)-1])

5 and 6


In [ ]:
a = list(range(0,10,2))

print(a[::-1])

[8, 6, 4, 2, 0]


In [ ]:
a = [[29, 'Rajesh'],[32, 'Ramesh'],[41, 'Dev']]

b = dict(a)

print(b.keys())

dict_keys([29, 32, 41])


In [ ]:
a = {1: "Rajesh",

2: "Ramesh",

3: "Dev"}

b = list(a)

print(b[0])

1


In [ ]:
a = tuple(range(0,5))

print(a.index(4))

4


In [ ]:
a = tuple(range(0,10,2))

a[4] = 6

print(a[4])

TypeError: 'tuple' object does not support item assignment

In [ ]:
a = {1,1,2,2,3,3,4,4,5,5}

print(a)

{1, 2, 3, 4, 5}


In [ ]:
a = {1,2,3,4,5}

a.add(6)

print(a)

{1, 2, 3, 4, 5, 6}


In [ ]:
A = 10
B = 20
if A > 5 & B > 15:
    print("One")
elif A < 5 & B < 15:
    print("Two")
else:
    print("None")

None


In [ ]:
#18.one, but one has given
A = 2

B = 10

if A > 0 and B%A==0:

    print("One", end=",")

elif B > 5 and B%2 == 1:

    print("Two", end=" ")

else:

    pass

One,

In [ ]:
A = 2

B = 3

print('Greater') if A//B==0 else print("Equal") if A//B==1 else print("Smaller")

Greater


In [ ]:
X = 10

if X >= 0:
    if X == 0:

        print('None')

    elif X //2 == 1:
        print('Two')

    elif X**2 ==100:

        if X%2 == 0:

            print("Three")

        else:

            print("Four")

    else:

        print("Five")

else:

    print("Six")



Three


In [ ]:
a = list(range(0,3))

b = []

for x in a:
    for j in range(len(a)-1, 0, -1):
        b.append(a[j])
        print(b)

[2]
[2, 1]
[2, 1, 2]
[2, 1, 2, 1]
[2, 1, 2, 1, 2]
[2, 1, 2, 1, 2, 1]


In [ ]:
i=5

while i>0:
    for i in range(0,3):
        if i > 1:
            i = i - 2
            print(i)
        else:
            i = i - 1

0


In [ ]:
i = 9
while i > 5:
    if i%2 == 0:
        i = i**2
        print(i)
    else:
        i = i**0.5
        print(i)

3.0


In [ ]:
a = 0
b = 1
i = 1

while i < 5:
    temp = a + b
    a = b
    b = temp
    print(temp, end=" ")
    i = i + 1

1 2 3 5 

In [ ]:
def func(self):
    if self%2==0:
        return None
func(10)

In [ ]:
def func(*self):
    for i in self:
        if i in list(range(0,100,10)):
            print("True", end=",")
        else:
            print("False")
func(10,15)

True,False


In [ ]:
def func(**self):
    for i in self.values():
        if i%2 == 0 and i%3 == 0 in list(range(0,10)):
            print("True", end=" ")
        else:
            print("False", end=" ")
func(first= 10, second= 20)

False False 

In [ ]:
y = lambda a,b: a//2 + b//2 - 2//a//b

y(12,4)

8

In [ ]:
sample = [12,22,32,42,52]

x = map(lambda a: a//10, sample)

print(list(x))

[1, 2, 3, 4, 5]


In [ ]:
def func(self):
    if self % 2 == 1:
        return False
    else:
        return True
sample= [12,24,23,3,5,2]
z = filter(func, sample)
print(list(z))

[12, 24, 2]


In [ ]:
def func(x, y, z):
    for i in x:
        for j in y:
            print(i, end="")
            print(j, end="")
    return None

a = [1,2,3]

b = [3]

c = [5,6,7]

func(a,b,c)

132333

In [ ]:
x = lambda x,y,z: x**y + z**x + y**x//z

x(1,1,3)

4

In [ ]:
class Myclass:
    def __init__(self):
        self.string = "Intellipaat"
        self.number = 2022
        obj = Myclass()
        print(obj.number, obj.string)

In [ ]:
class Myclass:
    def __init__(self):
        self.string = "Conor"
        self.number = 20
    def view(self):
        print(self.string[::-1], self.number//6)
obj = Myclass()
obj.view()

ronoC 3


In [ ]:
class myClass:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def view(self):
        print([self.name, self.age])
class myclass:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def view(self):
        print([self.name, self.age])
obj1 = myClass("Devon", 29)
obj2 = myclass("Levi", 28)
print([obj1.name, obj2.age])

['Devon', 28]


In [ ]:
class Name:
    def view(self):
        self.name = "Rajesh"
        return self.name
class Age:
    def view(self):
        self.age = 29
class Profession:
    def view(self):
        self.profession = "Teacher"

obj1 = Name()
obj2 = Age()
obj3 = Profession()
print(obj1.view(), obj2.view(), obj3.view())

Rajesh None None


In [ ]:
class Base:
    def __init__(self):
        self.name = "Ricky"
        self.age = 23
class Derived(Base):
    def __init__(self):
        super().__init__()
        self.profession = "Cricketer"
    def view(self):
        print(self.name, self.age, self.profession)
obj = Derived()
obj.view()

Ricky 23 Cricketer


In [ ]:
from abc import ABC, abstractmethod

class School(ABC):
    def __init__(self):
        self.name = "Levi"
        self.age = 29
obj = School()
obj.name

'Levi'

In [ ]:
class Poly:
    def method(self, a, b):
        return (a**b)
    def method(self, a, b,c):
        return (a*b*c)
obj = Poly()
obj.method(3,2)

TypeError: Poly.method() missing 1 required positional argument: 'c'

In [ ]:
class Parent:
    def __init__(self):
        self._name = "Levi"
        self.__age = 29
class Child(Parent):
    def __init__(self):
        Parent.__init__(self)
        self._name = "Devon"
    def view(self):
        return self._name
obj = Child()
obj.view()

'Devon'

In [ ]:
class Parent:
    def __init__(self):
        self._name = "Levi"
        self.__age = 29
class Child(Parent):
    def __init__(self):
        Parent.__init__(self)
        self._name = "Devon"
        self.__age = 28
    def view(self):
        return self.__age
obj = Child()
obj.view()

28

In [ ]:
class Parent:
    def __init__(self):
        self._name = "Rajesh"
        self.__age = 29
class Child(Parent):
    def __init__(self):
        Parent.__init__(self)
        self._name = "Ramesh"
    def view(self):
        return self.__age
obj = Child()
obj.view()

AttributeError: 'Child' object has no attribute '_Child__age'

In [ ]:
class Poly:
    def __init__(self):
        self.name = 'Rajesh'
        self.age = 29
    def view(self):
        return None
class Child(Poly):
    def __init__(self):
        Poly.__init__(self)
    def view(self):
        self.prof = "Student"
        super().view()
        return None
obj = Poly()
obj.view()

In [ ]:
class Poly:
    def __init__(self):
        self.name = 'Devon'
        self.age = 29
    def view(self):
        print(self.name)
class Child(Poly):
    def __init__(self):
        Poly.__init__(self)
    def view(self):
        self.prof = "Levi"
        super().view()
        return None
obj = Child()
obj.view()

Devon


In [ ]:
from multipledispatch import dispatch
class Poly:
    @dispatch(int, int)
    def method(self, a, b):
        return (a**b)
    @dispatch(int, int, int)
    def method(self, a, b,c):
        return (a*b*c)
obj = Poly()
print(obj.method(4,2))
print(obj.method(4,2,3))

16


24

In [ ]:
a = list(range(0,3))
range(len(a)-1, 0, -1)

range(2, 0, -1)

In [ ]:
#Numpy
import numpy as np

Array1 = np.array([[1, 2, 3], [4, 5, 6]])
Array2 = np.array([[2, 3], [3, 2]])

dot_product = np.dot(Array1, Array2)

print(dot_product)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
import numpy as np

array = np.array([10, 3, 1, 203, 404, 204, 20, 302, 30, 402, 192])

reverse_array = array[::-1]
print(reverse_array)

[192 402  30 302  20 204 404 203   1   3  10]


In [ ]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [ ]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))

b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [ ]:
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

result = np.vstack((array1, array2))
print(result)

[[ 1  2]
 [ 3  4]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
import numpy as np

array = np.array([10, 3, 1, 203, 404, 204, 20, 302, 30, 402, 192])
Elem_to_be_inserted = [1, 2, 3, 4]
position = np.where(array == 404)[0][0]

result = np.insert(array, position, Elem_to_be_inserted)
print(result)

[ 10   3   1 203   1   2   3   4 404 204  20 302  30 402 192]


In [ ]:
import numpy as np

k = 10  # Example constant value
matrix = np.full((3, 3), k)
print(matrix)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
np.eye(k)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j+1] = temp
    return array
bub_sort(np.array([20,14,25,16,45,60,12,9]))

array([60, 45, 25, 20, 16, 14, 12,  9])

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
reshaped_array = np.reshape(array, (5, 2))
print(reshaped_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
import numpy as np

sample = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
flattened_array = sample.flatten()

print(flattened_array)
print(flattened_array.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [ ]:
import numpy as np

Sample = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
result = Sample[0:3, 1]

print(result)

[2 5 8]


In [ ]:
import numpy as np

array1 = np.arange(20, 2, -1)
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

result = np.hstack((array1, array2))
print(result)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  1  2  3  4  5  6
  7  8  9 10]


In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)
result = np.hstack((array1, array2))
print("horizontal\n",result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
horizontal
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

A = np.array([[4], [12], [29]])
B = np.array([[13], [21], [4]])
print(A)
print(B)
result = np.cross(A.flatten(), B.flatten())
print(result)

[[ 4]
 [12]
 [29]]
[[13]
 [21]
 [ 4]]
[-561  361  -72]


In [ ]:
import numpy as np

A = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25])
B = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

result = np.corrcoef(A, B)
print(result)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

sample = {1: [1, 2], 2: [[1], [2]], 3: [[1, 2], [3, 4], [4, 5]], 4: [1], 5: [1, 2, 3, 4, 5]}

result = np.array([[k, v] for k, v in sample.items()], dtype=object)
print(result)

[[1 list([1, 2])]
 [2 list([[1], [2]])]
 [3 list([[1, 2], [3, 4], [4, 5]])]
 [4 list([1])]
 [5 list([1, 2, 3, 4, 5])]]


In [ ]:
import numpy as np

arr1 = np.array([[3, 2, 1], [6, 4, 5], [8, 7, 9]])

# Find the minimum element across the rows
min_rows = np.min(arr1, axis=1)

# Find the maximum element across the columns
max_cols = np.max(arr1, axis=0)

# Calculate the difference
difference = max_cols - min_rows

print(difference)

[7 3 2]


In [ ]:
import pandas as pd


In [ ]:
import numpy as np
x = [4,2,1,6,3,6,8,0,5,2,1,7,0,2]
np.var(x, ddof=1)

7.016483516483515

In [ ]:
A = np.array([[3,2],[4,1],[2,5]])
B = np.array([[6,11],[4,12],[2,15]])
np.cross(A,B)

array([21, 44, 20])

In [ ]:
A = np.array([4,5,6])
B = np.array([1,2,3])
np.hstack((B,A))

array([1, 2, 3, 4, 5, 6])

In [ ]:
A = np.array([[4],[5],[6]])
B = np.array([[1],[2],[3]])
np.column_stack((A,B))

array([[4, 1],
       [5, 2],
       [6, 3]])

In [ ]:
import numpy as np

sample = [42, 61, 39, 70, 8, 30, 52, 28, 95, 86, 35, 77, 80, 86, 1, 84, 90, 57, 45, 6, 1, 56, 60, 83, 24, 63, 93, 59, 92, 53]

# Calculate variance
variance = np.var(sample)

# Calculate standard deviation
std_deviation = np.std(sample)

print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Variance: 811.9599999999999
Standard Deviation: 28.49491182649983


In [ ]:
import numpy as np

array = np.array([17, 27, 80, 39, 72, 95, 52, 85, 8, 64, 36, 15, 62, 76, 66, 67, 59, 92])

# Calculate range
range_array = np.max(array) - np.min(array)

# Calculate quartiles
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

# Calculate interquartile range (IQR)
IQR = third_quartile - first_quartile

print("Range:", range_array)
print("Interquartile Range (IQR):", IQR)

Range: 87
Interquartile Range (IQR): 38.25


 In a skewed distribution, If the mean and median of a sample is 56, and 63 and the mode of the same is 65. The distribution graph of the sample will be ___?
Unskewed
None of the Above
Negatively Skewed
Positively Skewed

The mean, median, and mode provide insights into the skewness of a distribution:

If the mean is greater than the median, the distribution tends to be positively skewed.
If the mean is less than the median, the distribution tends to be negatively skewed.
If the mean is approximately equal to the median, the distribution is close to symmetrical.
In this case, the mean (56) is less than the median (63), indicating that the distribution is negatively skewed. Therefore, the correct answer is "Negatively Skewed".







In [ ]:
import numpy as np

# Sample data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

# Calculate Q1, Q3, and IQR
Q1 = 4
Q3 = 8.25
IQR = 4.5

# Calculate lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify suspected outliers
outliers = data[(data < lower_bound) | (data > upper_bound)]

print("Suspected outliers:", outliers)

Suspected outliers: []


In [ ]:
def my_function(*Students):
  print("The Top student is " + Students[0])

my_function("John", "Tobias", "Linus","Emil")


The Top student is John


In [ ]:
def my_function(b1, b2, b3):
  print("The Top Brand " + b3)

my_function(b1 = "Dell", b2 = "Lenova", b3 = "Logitech")

The Top Brand Logitech


In [ ]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


Single Asterisk allows the developer to pass a variable number of Positional parameters and automatically converts the input values in the form of tuples. At the same time, Double Asterisks allows the users to pass a variable number of Keyword parameters in the form of a Dictionary.


In Python, arguments can be passed to a function in two ways: positional arguments or keyword arguments: A positional argument is an argument that is passed to a function based on its position in the argument list. A Keyword argument is passed to a function by specifying the parameter name and its corresponding value

In [ ]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


In [ ]:
def fruits(sweet_fruits):
    for x in sweet_fruits:
        print(x)

sweet_fruits = ["apple", "banana", "cherry"]

fruits(sweet_fruits)

apple
banana
cherry


In [ ]:
def my_function(x):
  return 5 * x

print(my_function(3))

15


In [ ]:
#positional arguments
def my_function(x, /):
  print(x)

my_function(3)


3


In [ ]:
def my_function(x):
  print(x)

my_function(x = 3)

3


In [ ]:
# keyword arguments
def my_function(*, x):
  print(x)

my_function(x = 3)

3


In [ ]:
def my_function(a, b, /, *, c, d):
  print(a + b + c + d)

my_function(5, 6, c = 7, d = 8)


26


A lambda function in Python is a small anonymous function defined using the lambda keyword. It allows you to create a function without a proper name. Lambda functions can take any number of arguments, but they can only have one expression. They are often used when you need a simple function for a short period

In [ ]:
x = lambda a : a + 10
print(x(5))

15


In [ ]:
x = lambda a, b : a * b
print(x(5, 6))

30


WHY?The power of lambda is better shown when you use them as an anonymous function inside another function.

In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


In [ ]:
142
1**3

1

In [ ]:
4**3

64

In [ ]:
2**3

8

In [ ]:
64+8

72

In [ ]:
Here are the main differences between for and while loops in Python:

Syntax:
For Loop: The for loop is used to iterate over a sequence (such as lists, tuples, strings, etc.) or other iterable objects. It has the following syntax:
python
Copy code
for item in sequence:
    # Code block to be executed for each item
While Loop: The while loop is used to execute a block of code repeatedly as long as a specified condition is true. It has the following syntax:
python
Copy code
while condition:
    # Code block to be executed as long as condition is true
Use Cases:
For Loop: Typically used when you know the number of iterations beforehand or when you want to iterate over a collection of items.
While Loop: Generally used when you don't know the exact number of iterations beforehand, or when you want to repeat execution until a certain condition is met.
Initialization:
For Loop: The loop variable (e.g., item in the syntax example) is initialized with each item in the sequence in each iteration automatically.
While Loop: You need to initialize any variables used in the condition before the loop starts.
Termination:
For Loop: Terminates when all items in the sequence have been processed.
While Loop: Terminates when the condition specified becomes false.
Potential for Infinite Loop:
For Loop: Less prone to infinite loops since the number of iterations is typically known in advance.
While Loop: More prone to infinite loops if the condition is not properly updated within the loop, potentially leading to the loop running indefinitely.
Common Use Cases:
For Loop: Iterating over elements in a list, processing each character in a string, looping over a range of numbers, etc.
While Loop: Iterating until a certain condition is met (e.g., user input meets a specific requirement, a certain value is reached, etc.).
In summary, for loops are generally preferred when you know the number of iterations or want to iterate over a sequence, while while loops are useful when you need to repeat execution until a certain condition is met, and the number of iterations is not known in advance.

#1 Find the given number is Armstrong number or not
1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407
For example, let's take the number 153:

1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153

Here's how the process works:

Take an integer.
Break it into its individual digits.
Raise each digit to the power of the total number of digits.
Sum up these powered digits.
If the sum equals the original number, then it is an Armstrong number.

In [ ]:
num = int(input("Enter a number: "))
# Input: 407
sum = 0
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")
# Output: 407 is an Armstrong number

Enter a number: 153
153 is an Armstrong number


In [ ]:
#2.Write a program to check if the given strings are anagram or not.

In [ ]:
def check(s1, s2):

    if(sorted(s1)== sorted(s2)):
        print("The strings are anagrams.")
    else:
        print("The strings aren't anagrams.")

s1 = input("Enter string1: ")
# input1: "listen"
s2 = input("Enter string2: ")
# input2: "silent"
check(s1, s2)

Enter string1: listen
Enter string2: silent
The strings are anagrams.


#Write a program to print the following pattern.
1
1  2
1  2  3
1  2  3  4   
1  2  3  4  5

In [ ]:
def num(n):
    num = 1
    for i in range(0, n):
        num = 1
        for j in range(0, i+1):
            print(num, end=" ")
            num = num + 1
        print("\r")
n = 5
num(n)

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
for i in range(5):
    for j in  range(i+1):
        print('*',end=" ")
    print('\n')


* 

* * 

* * * 

* * * * 

* * * * * 



In [ ]:
# conditional statements -> if, else, elif

age = 13
is_voter_id = True

if(age >= 18 and is_voter_id == True):
    print('You are eligible to vote')
else:
    print('Not eligible')

Not eligible


In [ ]:
# greatest of 3 nums
num1 = 100
num2 = 200
num3 = 500

if (num1 > num2 and num1 > num3):
    print('num1 is greater')
elif(num2 > num1 and num2 > num3):
    print('num2 is greater')
else:
    print('num3 is greater')

num3 is greater


In [ ]:
while True:
    print("Hello")
    break


In [ ]:
#LISTS REAL TIME EXAMPLE
#Library management system
class Library:
    def __init__(self):
        # Initialize the library with an empty list of books
        self.books = []

    def add_book(self, book_name):
        # Add a new book to the library
        self.books.append(book_name)
        print(f"Book '{book_name}' has been added to the library.")

    def borrow_book(self, book_name):
        # Borrow a book from the library
        if book_name in self.books:
            self.books.remove(book_name)
            print(f"You have borrowed '{book_name}'.")
        else:
            print(f"Sorry, the book '{book_name}' is not available in the library.")

    def return_book(self, book_name):
        # Return a book to the library
        self.books.append(book_name)
        print(f"Book '{book_name}' has been returned to the library.")

    def display_books(self):
        # Display the list of available books in the library
        if self.books:
            print("Available books in the library:")
            for book in self.books:
                print(f"- {book}")
        else:
            print("No books are currently available in the library.")

# Main function to interact with the library system
def main():
    library = Library()

    while True:
        print("\nLibrary Management System")
        print("1. Add a Book")
        print("2. Borrow a Book")
        print("3. Return a Book")
        print("4. Display Available Books")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            book_name = input("Enter the name of the book to add: ")
            library.add_book(book_name)
        elif choice == '2':
            book_name = input("Enter the name of the book to borrow: ")
            library.borrow_book(book_name)
        elif choice == '3':
            book_name = input("Enter the name of the book to return: ")
            library.return_book(book_name)
        elif choice == '4':
            library.display_books()
        elif choice == '5':
            print("Exiting the Library Management System. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()


Library Management System
1. Add a Book
2. Borrow a Book
3. Return a Book
4. Display Available Books
5. Exit
Enter your choice: 2
Enter the name of the book to borrow: helen
Sorry, the book 'helen' is not available in the library.

Library Management System
1. Add a Book
2. Borrow a Book
3. Return a Book
4. Display Available Books
5. Exit
Enter your choice: 4
No books are currently available in the library.

Library Management System
1. Add a Book
2. Borrow a Book
3. Return a Book
4. Display Available Books
5. Exit
Enter your choice: 1
Enter the name of the book to add: Chetan Bhagat
Book 'Chetan Bhagat' has been added to the library.

Library Management System
1. Add a Book
2. Borrow a Book
3. Return a Book
4. Display Available Books
5. Exit
Enter your choice: 1
Enter the name of the book to add: Thirumanthiram
Book 'Thirumanthiram' has been added to the library.

Library Management System
1. Add a Book
2. Borrow a Book
3. Return a Book
4. Display Available Books
5. Exit
Enter your c

In [ ]:
#USING DICTIONARY REAL TIME EXAMPLE using LOG IN Credentials
database = {'virat':3345, 'sharan':9989, 'rashmi':9054, 'prashant':7732}

In [ ]:
username = input('Please enter your username : ').strip().lower()

if username in database.keys():
    password = int(input('Please enter your password : '))
    if password == database[username]:
        print('Hello', username.capitalize())
    else:
        print('Sorry but it seems your password is incorrect. Please try again')
else:
    print('Sorry but it seems that you are not in our database or the username entered is incorrect')
    response = input('Do you want to be added to the database? (Yes/No)').capitalize()

    if response == 'Yes':
        password = int(input('Please enter your password : '))
        database[username] = password
    else:
        print('Thank you for visiting. See you soon again!')

print(database)

Please enter your username : sdf
Sorry but it seems that you are not in our database or the username entered is incorrect
Do you want to be added to the database? (Yes/No)no
Thank you for visiting. See you soon again!
{'virat': 3345, 'sharan': 9989, 'rashmi': 9054, 'prashant': 7732, 'suganya': 1111}


In [ ]:
database['virat']

3345

In [ ]:
database.keys()

dict_keys(['virat', 'sharan', 'rashmi', 'prashant'])

In [ ]:
database.values()

dict_values([3345, 9989, 9054, 7732])

In [ ]:
username = input('please enter your username: ').strip().lower()


if username in database.keys():
    password = int(input('please enter your password: '))
    if password == database[username]:
        print('hello', username.capitalize())
    else:
        print('sorry but it seems your password is incorrect. please try again')

else:
    print('sorry but seems that you are not in our database or the username entered incorrect')
    response = input('do you want to be added to the data base? (Yes/No)').capitalize()

    if response == 'Yes':
        password = int(input('please enter your password: '))
        database[username] = password
    else:
        print('thank you for visiting. see you again!')

print(database)

please enter your username: suganya
please enter your password: 1111
hellow Suganya
{'virat': 3345, 'sharan': 9989, 'rashmi': 9054, 'prashant': 7732, 'suganya': 1111}


he if __name__ == "__main__": construct is a standard way in Python to ensure that certain code (typically the test or main routine) is executed only when the script is run directly, and not when it is imported as a module.

The line if __name__ == "__main__": followed by main() is a common construct in Python scripts. It is used to ensure that a block of code is only executed when the script is run directl

In [ ]:
class Dog:
    def __init__(self, name, age):
        self.name = name  # self.name is an instance attribute
        self.age = age    # self.age is an instance attribute

    def speak(self):
        print(f"{self.name} says woof!")

    def birthday(self):
        self.age += 1
        print(f"{self.name} is now {self.age} years old.")

# Create an instance of Dog
my_dog = Dog("Jimmy", 3)

# Call instance methods
my_dog.speak()      # Output: Buddy says woof!
my_dog.birthday()   # Output: Buddy is now 4 years old.

Jimmy says woof!
Jimmy is now 4 years old.


requests.get(url) is a function call in Python that sends an HTTP GET request to the specified URL using the requests library. This function is commonly used in web scraping and API consumption to retrieve web pages or data from web servers.


The HTTP status code is a numerical value that indicates the outcome of the HTTP request. It provides information about whether the request was successful, encountered an error, or requires further action.
Here are some common HTTP status codes:
200: OK - The request was successful.
404: Not Found - The requested resource was not found on the server.
500: Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request.



In Python regular expressions, the r prefix before a string literal denotes a raw string. When you use r'\b\w+\b', it tells Python to interpret the string exactly as it appears, without any special treatment of backslashes.



In the context of the expression re.findall(r'\b\w+\b', text), the pattern \b\w+\b represents a regular expression that matches whole words in the input text. Here's what each part of the pattern means:
\b: Represents a word boundary. It matches the empty string at the beginning or end of a word. It helps ensure that the pattern matches whole words and not parts of words.
\w+: Represents one or more word characters. A word character typically includes alphanumeric characters (letters and digits) and underscores.
\b: Another word boundary to ensure that the pattern matches whole words.
When you call re.findall(r'\b\w+\b', text), it searches the text string for all occurrences of whole words and returns them as a list of strings.


In the context of the response.content attribute in Python's requests library, content refers to the raw byte data of the HTTP response body.
When you make an HTTP request using requests.get(url) (or similar methods), the requests library sends the request to the specified URL and receives a response from the server. This response typically includes headers (metadata) and a body (the actual content).
The response.content attribute contains the raw byte data of the HTTP response body. It's useful when you want to access the response content in its original binary form, such as when downloading files, images, or other non-textual data from a web server.





In [ ]:
# Assignment 3
#Create a web scraping program to display the list of all words from Url(Wikipedia) using BeautifulSoup bs4.
#skills: functions, re

from bs4 import BeautifulSoup
import requests
import re

# Function to extract words from HTML page
def extract_words(url):
    # Send a GET request to the URL
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Extract text from HTML
        text = soup.get_text()

        # Use regular expression to find words
        words = re.findall(r'\b\w+\b', text)

        return words
    else:
        print("Failed to retrieve the HTML content.")
        return []

# Example usage:
url = "https://en.wikipedia.org/wiki/Artificial_intelligence"  # Replace with the URL of the HTML page you want to scrape
#url="Enter"
words = extract_words(url)
print("Words extracted from the HTML page:", words)

Words extracted from the HTML page: ['Artificial', 'intelligence', 'Wikipedia', 'Jump', 'to', 'content', 'Main', 'menu', 'Main', 'menu', 'move', 'to', 'sidebar', 'hide', 'Navigation', 'Main', 'pageContentsCurrent', 'eventsRandom', 'articleAbout', 'WikipediaContact', 'usDonate', 'Contribute', 'HelpLearn', 'to', 'editCommunity', 'portalRecent', 'changesUpload', 'file', 'Search', 'Search', 'Create', 'account', 'Log', 'in', 'Personal', 'tools', 'Create', 'account', 'Log', 'in', 'Pages', 'for', 'logged', 'out', 'editors', 'learn', 'more', 'ContributionsTalk', 'Contents', 'move', 'to', 'sidebar', 'hide', 'Top', '1Goals', 'Toggle', 'Goals', 'subsection', '1', '1Reasoning', 'and', 'problem', 'solving', '1', '2Knowledge', 'representation', '1', '3Planning', 'and', 'decision', 'making', '1', '4Learning', '1', '5Natural', 'language', 'processing', '1', '6Perception', '1', '7Social', 'intelligence', '1', '8General', 'intelligence', '2Techniques', 'Toggle', 'Techniques', 'subsection', '2', '1Search

Explanation
Initialization (__init__ Method):

__init__ is a special method called a constructor. It initializes the instance attributes.
self.name and self.age are instance attributes, which are initialized using the values passed to the constructor.
Instance Methods (speak and birthday):

The speak method uses self.name to access the instance’s name attribute.
The birthday method modifies the instance’s age attribute using self.age.
What Happens When You Call a Method
When you call my_dog.speak(), Python internally translates this to Dog.speak(my_dog). This means the instance my_dog is passed as the first argument to the speak method, which is why self is needed in the method definition to receive this argument.

In [ ]:
def calculate_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "F"
# Example usage:
score = float(input("Enter the student's score: "))

if score < 0 or score > 100:
    print("Invalid score. Score must be between 0 and 100.")
else:
    grade = calculate_grade(score)
    print("The student's grade is:", grade)

Enter the student's score: 89
The student's grade is: B


#Assignment 2
Blood pressure levels can vary based on age, and there are generally accepted ranges for normal blood pressure at different ages. Here's a general guideline for blood pressure levels based on age:
Problem Statement:

Children:
Normal blood pressure for children varies with age, height, and sex. A pediatrician can provide specific guidance based on these factors.

Teenagers (13-19 years old):
Normal blood pressure: Systolic (top number) less than 120 mm Hg and diastolic (bottom number) less than 80 mm Hg.
Elevated blood pressure: Systolic 120-129 mm Hg and diastolic less than 80 mm Hg.
Hypertension stage 1: Systolic 130-139 mm Hg or diastolic 80-89 mm Hg.
Hypertension stage 2: Systolic 140 mm Hg or higher or diastolic 90 mm Hg or higher.

Adults (20 years and older):
Normal blood pressure: Systolic less than 120 mm Hg and diastolic less than 80 mm Hg.
Elevated blood pressure: Systolic 120-129 mm Hg and diastolic less than 80 mm Hg.
Hypertension stage 1: Systolic 130-139 mm Hg or diastolic 80-89 mm Hg.
Hypertension stage 2: Systolic 140 mm Hg or higher or diastolic 90 mm Hg or higher.

Elderly (65 years and older):
Blood pressure goals may be different for older adults, and individualized treatment plans are recommended.


In [ ]:

def is_low_blood_pressure(systolic, diastolic):
    if systolic < 90 and diastolic < 60:
        return True
    else:
        return False
def blood_pressure_category(age, systolic, diastolic):

        if age < 13:
            print("Blood pressure norms for children vary. Please consult a pediatrician for guidance.")
        elif age >= 13 and age <= 19:
            if systolic < 120 and diastolic < 80:
                print("Normal blood pressure")
            elif systolic >= 120  and diastolic < 80:
                print("Elevated blood pressure")
            elif systolic >= 130 and diastolic <= 89:
                print("Hypertension stage 1")
            else:
                print("Hypertension stage 2")
        elif age >= 20 and age < 65:
            if systolic < 120 and diastolic < 80:
                print("Normal blood pressure")
            elif systolic >= 120 and diastolic < 80:
                print("Elevated blood pressure")
            elif (systolic >= 130 or systolic <= 139) and (diastolic >= 80 and diastolic <= 89):
                print("Hypertension stage 1")
            else:
                print("Hypertension stage 2")
        else:
            print("Blood pressure goals may be different for older adults. Individualized treatment plans are recommended.")
try:
    age = int(input("Enter age: "))
    if age <=0:
        raise Exception("Numbers 0 and below not accepted")
    elif age < 13:
        print("Blood pressure norms for children vary. Please consult a pediatrician for guidance.")
    elif age>=13:
        systolic = int(input("Enter systolic blood pressure: "))
        diastolic = int(input("Enter diastolic blood pressure: "))
        if systolic >=90 and diastolic >=60:
            print(f"Systolic: {systolic} mm Hg")
            print(f"Diastolic: {diastolic} mm Hg")
            blood_pressure_category(age, systolic, diastolic)

    if is_low_blood_pressure(systolic, diastolic):
        print("The blood pressure is low and need Medical Attention")
    else:
        pass
except ValueError:
    print("Enter proper value")
except:
    print("zero or lesser not accepted")
    print(f"your age is:{age} inappropriate")

finally:
    print("Thank you. Have a Good Day!")


In [ ]:
def is_valid_blood_pressure(systolic, diastolic):
    # Check for negative values
    if systolic < 0 or diastolic < 0:
        return False, "Negative values"

    # Check for extremely high values
    if systolic > 200 or diastolic > 120:  # Example thresholds (adjust as needed)
        return False, "Extremely high values"

    # If both systolic and diastolic values pass the checks, return True
    return True, "Valid"

def Blood_pressure_levels(systolic,diastolic):
    if systolic < 120 and diastolic < 80:
        print("Normal blood pressure")
    elif systolic >= 120  and diastolic <= 80:
        print("Elevated blood pressure")
    elif systolic >= 130 and diastolic <= 89:
        print("Hypertension stage 1")
    else:
        print("Hypertension stage 2")

def is_low_blood_pressure(systolic, diastolic):
    if systolic < 90 and diastolic < 60:
        return True
    else:
        return False
systolic = int(input("Enter systolic blood pressure: "))
diastolic = int(input("Enter diastolic blood pressure: "))
#Validation for systolic and diastolic values
valid, reason = is_valid_blood_pressure(systolic, diastolic)
if valid:
    print("Blood pressure values are valid.")
else:
    print("Invalid blood pressure values. Reason:", reason)

print(f"Systolic: {systolic} mm Hg")
print(f"Diastolic: {diastolic} mm Hg")

if systolic>=90 and diastolic >=60:
    Blood_pressure_levels(systolic,diastolic)
else:
    if is_low_blood_pressure(systolic, diastolic):
        print("The blood pressure is low and need Medical Attention")
    else:
        pass


In [ ]:
1/3

0.3333333333333333

In [ ]:
4,6,2,8,9,7,-1,36,-28

(4, 6, 2, 8, 9, 7, -1, 36, -28)

In [ ]:
-28,-1,2,4,6,7,8,9,36